# Physical-boundary regression gate; globbing here audits files, never selects
# production translation units (which CMakeLists.txt enumerates explicitly).
cmake_minimum_required(VERSION 3.20)
file(GLOB flat_sources "${ROOT}/src/*.c" "${ROOT}/src/*.h" "${ROOT}/src/*.cpp" "${ROOT}/src/*.hpp")
if(flat_sources OR EXISTS "${ROOT}/gui")
    message(FATAL_ERROR "Application sources must live in module directories under src")
endif()

file(STRINGS "${MANIFEST}" compiled_files)
file(GLOB_RECURSE sources RELATIVE "${ROOT}"
    "${ROOT}/src/*.c" "${ROOT}/src/*.h" "${ROOT}/src/*.cpp" "${ROOT}/src/*.hpp")
foreach(path IN LISTS sources)
    if(path MATCHES "\\.(cpp|hpp)$" AND NOT path MATCHES "^src/gui/qt/")
        message(FATAL_ERROR "C++ outside Qt frontend: ${path}")
    endif()
    file(READ "${ROOT}/${path}" text)
    string(REGEX MATCHALL "#include[ \t]+\"[^\"]+\"" includes "${text}")
    get_filename_component(directory "${ROOT}/${path}" DIRECTORY)
    foreach(include IN LISTS includes)
        string(REGEX REPLACE "#include[ \t]+\"([^\"]+)\"" "\\1" header "${include}")
        if(header MATCHES "\\.(c|cpp)$")
            message(FATAL_ERROR "Implementation inclusion instead of separate compilation: ${path}: ${header}")
        endif()
        if(EXISTS "${ROOT}/src/${header}")
            get_filename_component(header_directory "${ROOT}/src/${header}" DIRECTORY)
            if(header MATCHES "(_internal|_utils)\\.h$" AND NOT directory STREQUAL header_directory)
                message(FATAL_ERROR "Private helper/owner header crosses module: ${path}: ${header}")
            endif()
        elseif(NOT EXISTS "${directory}/${header}" AND NOT header STREQUAL "yyjson.h")
            message(FATAL_ERROR "Missing or non-module-qualified include: ${path}: ${header}")
        endif()
    endforeach()
    if(path MATCHES "\\.(c|cpp)$")
        if(NOT GUI AND path MATCHES "^src/gui/")
            continue()
        endif()
        if(NOT path IN_LIST compiled_files)
            message(FATAL_ERROR "Source omitted from explicit production targets: ${path}")
        endif()
    endif()
endforeach()
message(STATUS "Source layout, private boundaries and explicit target coverage passed")
